### ISSUE TITLE
Callback Prefix

### ISSUE THREAD

**Issue by AlexeyBogdan95** [vippsas/vipps-signuplogin-api#2]
Good time! I have a question related to LoginCallbackPrefix. Should the host of the callback prefix be `https://`or it can be `http://`? Thank you!

**Comment by akhlaqahmadbitdegree** [comment]
Sorry, I am not working on vipps-api more.
Thanks

**Comment by cloveras** [comment]
Hi @AlexeyBogdan95 

We support both, but prefer and recommend HTTPS.

Christian, Vipps

**Comment by AlexeyBogdan95** [comment]
@cloveras thank you for the reply!
