### ISSUE TITLE
signup/v1/loginRequests/{requestId} usually responds FAILURE

### ISSUE THREAD

**Issue by AlexeyBogdan95** [vippsas/vipps-signuplogin-api#3]
steps for reproduce: 
- call initiateLogin
- get RequestId and Link(is app false)
- redirect by link and enter phone number
- open vipps MT app and confirm log in.
- redirect to fallback url is called
- call signup/v1/loginRequests/{requestId}

**Comment by AlexeyBogdan95** [comment]
Hi @cloveras 

https://apitest.vipps.no/signup/v1/loginRequests
Request body:
            merchantInfo =
            {
               callbackPrefix = https://ptsv2.com/t/h7xyy-1546422109/post,
               consentRemovalPrefix = http://35.156.171.22:9082/api/vipps/removeconsent,
               fallBack = http://35.156.171.22:9082/,
               isApp = false,
               merchantSerialNumber = /* value provided by dev portal */,
            }

This API method works well. I usually get RequestId and Url. When I finish the steps described above Vipps is redirected to`fallBack` url. As for callBack I set dump server and it catches callback response. 
But when I call https://apitest.vipps.no/signup/v1/loginRequests/7073(for example) I get the following response body
 {
   requestId: 7073,
   status: FAILURE
 }

@cloveras let me know if you need more information from my side. Thank you!

**Comment by AlexeyBogdan95** [comment]
There is a result that dump server caught.
![screenshot 13](https://user-images.githubusercontent.com/14297695/50636097-d7e91100-0f65-11e9-9864-5482e7c0675d.png)

**Comment by AlexeyBogdan95** [comment]
@cloveras any ideas?

**Comment by cloveras** [comment]
Hi @AlexeyBogdan95 

I did some quick asking around, but no solution, sorry. I have notified the ecom/signup team, and hope they can help soon. 

We normally use email for Vipps issues, as described on https://github.com/vippsas/vipps-developers/blob/master/contact.md, but we try to help here too.

Christian, Vipps

**Comment by torors** [comment]
This endpoint (on the test environment, haven't tested live) now returns

```
[
    {
        "errorCode": "500",
        "errorMessage": "Something went wrong from Vipps Server side"
    }
]
```
for any {{requestId}}

I initially thought this was a bug in my implementation, but testing this with the Postman test suite you have provided returns the same.

Please fix? :o

**Comment by AlexeyBogdan95** [comment]
@torors I recommend you sending issues to integration@vipps.no
